name: gwelcome_front
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

#dependencies:
#  flutter:
#    sdk: flutter
#  url_launcher: ^6.0.0
#
#
#  cupertino_icons: ^1.0.2
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  http: ^0.13.3
#
#  flutter_lints: ^2.0.0

dependencies:

  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_secure_storage: ^4.2.1
  url_launcher: ^6.0.12
  kakao_flutter_sdk_common: ^1.3.1
  kakao_flutter_sdk: ^1.7.0 # 전체 추가
  kakao_flutter_sdk_user: ^1.7.0 # 카카오 로그인
  kakao_flutter_sdk_talk: ^1.7.0 # 카카오톡 메시지, 카카오톡 소셜(프로필 가져오기, 친구 목록 가져오기)
  kakao_flutter_sdk_share: ^1.7.0 # 카카오톡 공유
  kakao_flutter_sdk_navi: ^1.7.0 # 카카오내비
  kakao_flutter_sdk_friend: ^1.7.0 # 카카오톡 소셜(피커: 친구 선택하기)


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0
  animations: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.3


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/design_course/
    - assets/fitness_app/
    - assets/hotel/
    - assets/introduction_animation/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
  
